### ISSUE TITLE
Player gets kicked using Lift NCP

### ISSUE THREAD

**Issue by Jumpy91** [croxis/Lift#148] opened 2017-09-29 20:33 UTC
Hey,

thanks for your nice and long living Plugin.

Im expiring the bug, that if a player uses a lift he gets kicked by NCP. Following statement is written to logfile.
[NoCheatPlus] <Playername> failed SurvivalFly: tried to move: -321.66, 63.50, 132.40 -> -321.66, 55.46, 132.40, d=8.04 (data_reset+vdistrel). VL 1702.
<Playername> lost connection: Kicked for flying (or related)
[NoCheatPlus] (CONSOLE) Kicked <Playername> : Kicked for flying (or related)

In NCP-Config nothing has been editied manually.

Im using this Versions:
>ncp version
[22:31:44 INFO]: ---- Version information ----
[22:31:44 INFO]: #### Server ####
[22:31:44 INFO]: git-Spigot-7754231-94b0980 ~MC: 1.12.2~
[22:31:44 INFO]:   detected: 1.12.2
[22:31:44 INFO]: #### NoCheatPlus ####
[22:31:44 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1113
[22:31:44 INFO]: MCAccess: 1.4.5-1.11.2|? / CB-Reflect
[22:31:44 INFO]: Features:
[22:31:44 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
[22:31:44 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[22:31:44 INFO]:   defaults: pvpKnockBackVelocity
[22:31:44 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[22:31:44 INFO]: Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
[22:31:44 INFO]: #### Related Plugins ####
[22:31:44 INFO]: CompatNoCheatPlus v6.6.4-RC-sMD5NET-b88 | ProtocolLib v4.4.0-SNAPSHOT-b389 | ProtocolSupport v4.28-dev

>lift version
Lift 56

Thanks for your help :)

**Comment by RoboMWM** [comment] 2017-12-30 02:58
What does the lift plugin do? If it's literally having them float in air (presumably on top of a fake block?) then NCP is functioning as intended; the lift plugin needs to add exemptions for NCP and the like to avoid anticheat violations.

**Comment by khlfkk** [comment] 2018-04-20 12:51
I reported in spigot about 10 months but the developer is still ignored it. So in your life you need  lucky to meet a good developer. So far you can use Skript to cancel fall damage as temporary solution.

**Comment by croxis** [comment] 2018-07-21 20:36
Should be fixed

**Closed by croxis** 2018-07-21 20:36 UTC
